# Generated by Django 6.0.8 on 2026-09-26 17:52

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Handled",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("message_id", models.UUIDField(null=True)),
                ("name", models.CharField(max_length=255)),
                ("key", models.CharField(blank=True, max_length=255)),
                ("seq", models.IntegerField(null=True)),
                ("attempt", models.IntegerField(default=1)),
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
            ],
        ),
    ]
