# Generated by Django 6.0.8 on 2026-09-26 17:48

import django.core.serializers.json
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutboxMessage",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("message_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("event", "Event"), ("job", "Job")], default="event", max_length=5
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Event type, or the job's registered name.", max_length=255
                    ),
                ),
                (
                    "payload",
                    models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        blank=True,
                        help_text="Messages sharing a key are processed one at a time, in insertion order.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("destination", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivered", "Delivered"),
                            ("dead", "Dead"),
                        ],
                        default="pending",
                        max_length=9,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField()),
                ("backoff", models.CharField(max_length=11)),
                (
                    "run_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        help_text="Not claimed before this time.",
                    ),
                ),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("locked_by", models.CharField(blank=True, max_length=100)),
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("last_traceback", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "outbox message",
                "indexes": [
                    models.Index(
                        condition=models.Q(("status", "pending")),
                        fields=["id"],
                        name="outbox_pending_idx",
                    ),
                    models.Index(
                        condition=models.Q(
                            ("key__isnull", False), ("status__in", ["pending", "dead"])
                        ),
                        fields=["key", "id"],
                        name="outbox_key_unfinished_idx",
                    ),
                    models.Index(fields=["status", "completed_at"], name="outbox_completed_idx"),
                ],
            },
        ),
    ]
