# Generated by Django 6.0.8 on 2026-09-29 16:23

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reliable_outbox", "0002_notify_trigger"),
    ]

    operations = [
        migrations.CreateModel(
            name="InboxMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("consumer", models.CharField(max_length=100)),
                ("message_id", models.CharField(max_length=255)),
                (
                    "received_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
            ],
            options={
                "verbose_name": "inbox message",
                "indexes": [models.Index(fields=["received_at"], name="inbox_received_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("consumer", "message_id"), name="inbox_unique_message"
                    )
                ],
            },
        ),
    ]
